collated: true
variants:
- name: default
  context:
    component: "list-item"
    nestedMods: [with-border-gradient]
    listItems:
    - caption:
        top: Наша продукция продается в
        body: 123
        bottom: городах России и СНГ
      component: "list-item--only-caption_extended"
    - icon: /assets/images/icons/benefits/2.png
      label: Более <strong>1 000 наименований</strong> в ассортименте
    - icon: /assets/images/icons/benefits/3.png
      label: Более <strong>1 000 наименований</strong> в ассортименте
    - icon: /assets/images/icons/benefits/4.png
      label: Более <strong>1 000 наименований</strong> в ассортименте
    bootstrap:
      cols: col
