context:
  contactsBlocks:
    - customClassList: mb-5
      id: map-moscow
      address: "143000, Россия,<br/>
                Mосковская обл.,<br/>
                г. Одинцово,<br/>
                ул. Транспортная д. 2"
      phones:
        - +7(495) 926-20-64
        - +7(495) 926-20-65
        - +7(495) 789-32-76
        - +7(495) 789-36-34
        - +7(495) 926-69-55

      anotherContacts:
        - 'info@politek-ptk.ru'
        - 'Время работы: с 8 до 17'

    - id: map-tula
      address: "143000, Россия,<br/>
                Тульская обл.,г.Тула,<br/>
                ул.Щегловская<br/>
                засека, д.31"
      phones:
        - +7 (4872) 70-23-36 <br/> (многоканальный)

      anotherContacts:
        - 'info@politek-ptk.ru'
        - 'Время работы: с 8 до 17'
