context:
  promoMaterials:
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк

  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
  - priceLabel: ""
    icon: /assets/images/catalog/1.png
    label: Коммерческое предложение ООО Политэк
