context:
  description: "<h3>Требования к перевозке</h3>
  <p>Хранение готовой продукции (труб и фитингов) допускается на открытых площадках в упаковке, не пропускающей ультрафиолетовые лучи, не более 6 месяцев.</p>
  <p>При хранении готовой продукции необходимо соблюдать размеры отступов:
  от приборов отопления – 0,2 м, от источников освещения – 0,2 м, от пола – 0,15 м, между поддонами и контейнерами в штабеле – 0,05-1 м.</p>
  <p>Фитинги следует хранить в коробках, контейнерах, ящиках и т.п., необходимо оберегать от ударов, механических нагрузок и от повреждений колющими, режущими предметами и инструментами их поверхности.</p> <br />
  <h3>Требования к хранению</h3>
  <p>Хранение готовой продукции (труб и фитингов) допускается на открытых площадках в упаковке, не пропускающей ультрафиолетовые лучи, не более 6 месяцев.<br>
  При хранении готовой продукции необходимо соблюдать размеры отступов:<br/>
  от приборов отопления – 0,2 м, от источников освещения – 0,2 м, от пола – 0,15 м, между поддонами и контейнерами в штабеле – 0,05-1 м.</p>
  <p>Фитинги следует хранить в коробках, контейнерах, ящиках и т.п., необходимо оберегать от ударов, механических нагрузок и от повреждений колющими, режущими предметами и инструментами их поверхности.</p>
  <p>Хранение готовой продукции (труб и фитингов) допускается на открытых площадках в упаковке, не пропускающей ультрафиолетовые лучи, не более 6 месяцев.</p>
  <p>При хранении готовой продукции необходимо соблюдать размеры отступов:<br/>
  от приборов отопления – 0,2 м, от источников освещения – 0,2 м, от пола – 0,15 м, между поддонами и контейнерами в штабеле – 0,05-1 м.</p>
  <p>Фитинги следует хранить в коробках, контейнерах, ящиках и т.п., необходимо оберегать от ударов, механических нагрузок и от повреждений колющими, режущими предметами и инструментами их поверхности.</p>"
