context:
  mods: [gosts]
  gostList:
    - id: СН 550-82
      title: "«Инструкция по проектированию технологических трубопроводов из пластмассовых труб»"
    - id: ГОСТ 123-12522
      title: "«Нормы по проектированию технологических трубопроводов из полипропилена»"
    - id: СН 550-82
      title:  "«Инструкция по проектированию технологических трубопроводов из пластмассовых труб»"
    - id: ГОСТ 123-12522
      title: "«Нормы по проектированию технологических трубопроводов из полипропилена»"
    - id: СН 550-82
      title:  "«Инструкция по проектированию технологических трубопроводов из пластмассовых труб»"
    - id: ГОСТ 123-12522
      title: "«Нормы по проектированию технологических трубопроводов из полипропилена»"
