context:
  orderBtn:
    label: Оформить заказ
    href: cart-template
    customClassList: mr-3
  callbackBtn:
    label: Заказать звонок
    customClassList: 'callbackBtn modal-link'
    href: "javascript:;"
    attrs:
      'data-modal-target': "#call-back"
