context:

  # Services modals
  services:
    - title: "Резка стекла и зеркал"
      description: '<p>Резка изделий происходит из листов 3210*2250мм</p>
      <p>Ежедневно в ассортименте более 40 видов стекла и зеркал - толщины от
      3 до 19мм, прозрачное, осветлённое, матовое стекло, тонированные (бронза,
      серое), зеркала серебро, осветлённое, бронза, графит, красное, пурпурное,
      2 вида золотого, а также 10 видов состаренных зеркал.</p>
      <p>&nbsp;</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>все размеры для изготовления стекла и зеркал принимаются в миллиметрах</li>
          <li>(1м = 100 см = 1000мм)</li>
          <li>резка закалённого стекла абсолютно невозможна!</li>
          <li>изогнутные стёкла, а также бутылки и графины и т.п. не разрезаем!</li>
          <li>рифлённого, узорчатого и витражного стекла в ассортименте нет.</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией и ТУ по резке стекла и зеркал</p>'
      image: "/assets/images/services/demo-service.png"

    - title: "Обработка кромки"
      description: '<p>Обработка кромки стекла и зеркал – шлифовка и полировка производятся на станках.</p>
      <p>Минимальный размер детали для обработки 90*90мм (для прямолинейных изделий) и диаметр 150мм (для криволинейных изделий); максимальный 3200мм и диаметр 2100мм, соответственно. </p>
      <p>Торец стекла после обработки представляет собой трапецию – ровный обработанный торец, с 2 фасками под 45° (ширина фаски от 1 до 3 мм, в зависимости от толщины стекла). Такой вид обработки называется также &laquo;еврокромка&raquo;.</p>
      <p>Отличие полировки от шлифовки в оптической прозрачности полированного торца (шлифованная поверхность непрозрачная, матовая).</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>По умолчанию, при выборе в калькуляторе обработки, мы производим полировку изделия &ndash; если для вас актуальна именно шлифовка, уточняйте это!</li>
          <li>Для последующей закалки изделия его торец обязательно должен быть обработан!</li>
          <li>Стекло или зеркало с обработанной кромкой более прочное по сравнению с таким же без обработки (связано с отсутствием микросколов и микротрещин на необработанной кромке)</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf </a>с подробной информацией и ТУ по обработке стекла и зеркал</p>'

      image: ""
    - title: "Сверление и фрезеровка"
      description: '<p>Сверление и фрезеровка стекла – процесс создания сквозных отверстий, внутренних и внешних вырезов в листовом стекле. Минимальный размер детали для сверления и фрезеровки 100*100мм; максимальный размер для сверления 3200*2200мм, для фрезеровки 1400*3000мм.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>Внутренний край отверстия/выреза имеет шлифованную матовую поверхность!</li>
          <li>Если изделие с отверстиями/вырезами должно быть закалено, оно обязательно должно соответствовать <u>параметрам для закалки</u>!</li>
          <li>На чертежах обязательно указывайте диаметр отверстий и расстояния от края стекла до центра каждого из отверстий в миллиметрах.</li>
          <li>Зеркала с отверстиями более хрупкие, для них рекомендуем наклеивать противоосколочную плёнку безопасности на сторону амальгамы.</li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией и ТУ по сверлению и фрезеровке стекла и зеркал.</p>'
      image: ""

    - title: "Фацет"
      description: '<p>Фацет &ndash; это широкая полированная фаска (от 5 до 40мм) на лицевой стороне стекла или зеркала.</p>
      <p>Минимальный размер детали для обработки фацета 120*120мм, максимальный 3200*2100мм.</p>
      <p>Для стекла и зеркал толщиной 4мм максимальная ширина фацета 20мм, для стекла от 6мм и более &ndash; ширина фацета до 40мм.</p>
      <div class="service-modal__attention">
          <p>&nbsp;Обратите, пожалуйста, внимание:</p>
          <ul>
              <li>Фацет для матового стекла можно сделать с глянцевой или с матовой стороны, уточняйте этот момент при заказе!</li>
              <li>Для стекла толщиной от 8мм кромка при изготовлении фацета обязательно полируется.</li>
              <li>Двусторонний фацет &ndash; фацет на обеих сторонах детали, двойной фацет &ndash; фацет разной ширины на одной стороне детали.</li>
          </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf </a>с подробной информацией и ТУ по обработке фацета на стекле и зеркалах.</p>'
      image: ""

    - title: "Закалка стекла"
      description: '<p>Закалка &ndash; процесс высоко-температурной обработки стекла, результатом которого является 5 кратное увеличение его прочности и эффект безопасного разрушения (при разбитии закалённое стекло распадается на мелкие травмобезопасные осколки).</p>
      <p>Закалка обязательна при использовании стекла в качестве дверей, душевых кабин, для кухонных фартуков, межкомнатных перегородок, балконных и лестничных ограждений; закалка желательна для стеклянных полок, столешниц, стеклянной мебели.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
            <li>Минимальный размер для закаливаемого стекла 200*300мм</li>
            <li>Зеркала, узорчатые и рифлёные стёкла не закаливаются!</li>
            <li>При закаливании стекла, особенно тонкого возможно появления отклонения от плоскости до 2-3мм</li>
            <li>Закалённое стекло НЕВОЗМОЖНО разрезать, просверлить, сделать вырез и т.п. При попытке воздействий подобного плана происходит разрушение стекла.</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией и ТУ по закалке стекла.</p>'
      image: ""

    - title: "Замеры и консультации"
      description: '<p>Замеры и консультации проводятся опытным квалифицированным персоналом компании. График замеров понедельник-суббота с 10:00 до 18:00. Стоимость замера в Москве 1000 рублей, замер в МО &ndash; 1500 рублей. При проведении замера обязательно должен присутствовать
          заказчик или компетентный представитель, которому передаются копия бланка замера и все необходимые ТУ для конкретного вида изделий, в соответствии с которыми производится подготовка поверхности, зоны монтажа.</p>
      <div class="service-modal__attention">
          <p><strong>Обратите, пожалуйста, внимание:</strong></p>
          <ul>
              <li>При необходимости изготовления жёсткого шаблона обязательно уведомлять об этом менеджера до начала замера!</li>
              <li>Наша компания не производит замер и замену окон, рам и стеклопакетов, а также стеклянных элементов деревянной мебели.</li>
          </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с договором на проведение замеров и консультаций.</p>'
      image: ""

    - title: "Доставка стекла"
      description: '<p>Доставка стекла производится на специализированых автомобилях компании. График доставки понедельник-суббота с 10:00 до 18:00. Стоимость доставки в Москве 1500 рублей, доставка по МО &ndash; 2500 рублей.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
            <li>Доставка осуществляется до подъезда, при необходимости подъёма заказа на этаж уведомляйте об этом менеджера (услуга подъёма оплачивается отдельно).</li>
            <li>Доставка осуществляется во временно интервал равный 2 часам.</li>
            <li>Время ожидания клиента на адресе до 30 минут. Повторный выезд платный, согласно прайса.</li>
            <li>При получении изделий внимательно проверяйте его на комплектность, соответствие данным заказа и целостность, после приёмки изделий претензии на некомплектность, целостность, сколы, царапины и т.п. не принимаются, согласно статье № закона &laquo;О
                защите прав потребителей&raquo;.</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией по доставке.</p>'
      image: ""

    - title: "Монтаж изделий"
      description: '<p>Монтажи проводятся опытным квалифицированным персоналом компании. График монтажей понедельник-суббота с 10:00 до 18:00. Согласование даты проведения монтажа осуществляется в течении двух рабочих дней после уведомления заказчика о готовности изделий и укомплектованности заказа. При проведении замера обязательно должен присутствовать заказчик или компетентный представитель, заказчика.  Минимальная стоимость монтажных работ 4000 рублей.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>При необходимости оформления пропусков на въезд автомобиля, заявок на монтажников, данных на внос и вынос материалов и инструмента ответственность за их своевременное и верное оформление лежит на заказчике, либо представителе заказчика.</li>
          <li>Доставка осуществляется во временной интервал равный 2 часам.</li>
          <li>Время ожидания клиента на адресе до 30 минут. Повторный выезд платный, согласно прайса.</li>
          <li>При изготовлении изделий для последующего монтажа по данным заказчика, без проведения замера представителем компании, ответственность за несоответствие предоставленных размеров фактическим лежит на заказчике. </li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией по доставке.</p>'
      image: ""

    - title: "Покраска стекла"
      description: '<p>Покраска стекла осуществляется акриловыми красками на водной основе по каталогу RAL Classic.</p>
      <p>Применимо для вставок межкомнатных дверей, мебельных фасадов, шкафов купе, офисных перегородок, кухонных фартуков, стеклянной мебели, стеновых панелей.</p>
      <p>Нанесённая краска обладает высокими показателями водостойкости, твердости и адгезии, безвредна и пожаробезопасна.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
            <li>Покраска по умолчанию производится с обратной стороны стекла, т.е. воспринимается через стекло и поверхность покраски защищена от воздействий.</li>
            <li>Для точной цветопередачи белого цвета и светлых тонов желательно выбирать осветлённое стекло (без зеленоватого оттенка)</li>
            <li>Изделия, покрашенные разными партиями в один и тот же RAL могут отличаться друг от друга оттенками.</li>
            <li>Окрашенные изделия не прозрачны и не должны восприниматься на просвет</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf </a>с подробной информацией и ТУ по покраске стекла.</p>'
      image: ""

    - title: "Пескоструйная обработка"
      description: '<p>Пескоструйная обработка стекла даёт эффект матирования. Возможно обработать одну или обе стороны стекла, как всю поверхность целиком (сплошное), так и по заданному узору (выборочное матирование).</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
            <li>Пескоструйную обработку объёмных изделий не осуществляем.</li>
            <li>Установка матовых стекол в душевой осуществляется обязательно матовой стороной в сторону обратную от попадания воды.</li>
            <li>Матовая поверхность более восприимчива к загрязнениям, чем глянцевая.</li>
        </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией и ТУ по покраске стекла.</p>'
      image: ""

    - title: "УФ-склейка"
      description: '<p>Склейка объёмных конструкций из стекла, приклеивание к стеклу металлической фурнитуры возможны благодаря особым свойствам специального уф-отверждаемого клея. Надёжное и долговременное склеивание определяется правильным подбором уф клея. </p>
      <p>Специалистами нашей компании производится изготовление стеклянных витрин, подиумов, стеклянной мебели и других 3D конструкций из стекла.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>Помимо услуг по изготовлению конструкций мы осуществляем продажу уф клея и ламп для ультрафиолетовой склейки.</li>
          <li>Уф склейку давальческого материала (стекла и фурнитуры) не производим. </li>
          <li>Термостойкость уф клея находится в пределах от -40 до +120°С, при необходимости разобрать склеенную конструкцию клеевой шов нужно нагревать промышленным феном.</li>
          <li>Большинство разновидностей уф клея обладают устойчивостью к влажности, но их нельзя использовать для склейки аквариумов, для этих целей применяют специальные силиконовые клеи.</li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией по уф-склейке.</p>'
      image: ""

    - title: "Изготовление триплекса"
      description: '<p>Два и более стёкол, склеенных между собою прозрачной (цветной или матовой) плёнкой называются триплекс. В процессе триплексования стёкла приобретают дополнительные функции – увеличенная прочность, безопасность при повреждении, звукоизолирующие свойства, блокирование солнечного уф-излучения, а также декоративные возможности. </p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>Для перегородок и дверей, как правило используется закалённый триплекс 4+4, 5+5, 6+6мм, в качестве ступеней, фрагментов пола 8+8+8, 10+10+10, 12+12+12мм, для столешниц и лестничных ограждений вполне подойдёт 5+5, 6+6мм.</li>
          <li>Внутрь триплекса можно разместить красивую ткань, уф печать, броне плёнку, детские рисунки и даже гербарий. </li>
          <li>Иногда интересного эффекта позволяет достичь «битый триплекс» - когда среднее из трёх закалённых стекол специально разбивают и получается изделие с уникальным узором из маленьких фрагментов битого стекла внутри.</li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией по триплексу.</p>'
      image: ""

    - title: "Фотопечать на стекле"
      description: '<p>Фотопечать на стекле осуществляется по технологии прямой печати уф-отверждаемыми чернилами с высоким разрешением 1440 dpi.</p>
      <p>Получаемый отпечаток экологически чист, не выцветает от солнца, устойчив к истиранию, выдерживает нагрев до 80&deg;С</p>
      <div class="service-modal__attention">
          <p><strong>Обратите, пожалуйста, внимание:</strong></p>
          <ul>
              <li>Печать по умолчанию производится с обратной стороны стекла, т.е. воспринимается через стекло и поверхность печати защищена от воздействий.</li>
              <li>Если в макете преобладают белые цвета и светлые тона, то для точной цветопередачи печати желательно выбирать осветлённое стекло (без зеленоватого оттенка)</li>
              <li>Макет для печати должен быть в размер 1:1, в формате Tiff, CMYK, 150 dpi</li>
              <li>Варианты изображений вы можете подобрать, к примеру, тут <a href="http://www.shutterstock.com" rel="nofollow" target="_blank">www.shutterstock.com</a> или тут <a href="http://www.otrisovki.ru/catalog/skinali" rel="nofollow" target="_blank">www.otrisovki.ru/catalog/skinali</a></li>
          </ul>
      </div>
      <p>&nbsp;</p>
      <p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией и ТУ по печати на стекле.</p>'
      image: ""

    - title: "Зеркальное панно"
      description: '<p>Зеркальное панно – комбинация отдельных зеркальных фрагментов тщательно подогнанных друг к другу. Как правило зеркала в панно имеют фацетную обработку от 5 до 20мм. Самые распространённые фигуры – ромбы, треугольники, квадраты, прямоугольники. Панно может быть, как смонтировано на месте, так и доставлено в готовом виде, приклеенном на подложку. Между отдельными элементами панно допустимы зазоры не более 2мм.</p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>На общий (внешний) габарит панно (площадью до 1,5 кв.м.) допустима погрешность в +/- 5мм</li>
          <li>Стена, на которую планируется клеить панно должна быть максимально выровненной по плоскости, как минимум прогрунтована, а лучше покрашена в чёрный или серебристый цвет масляной краской (например, МА-15)</li>
          <li>При затирке швов в панно, или по периметру цельного зеркала нельзя использовать затирки на цементной и эпоксидной основе!</li>
          <li>Во время ухода за зеркальным панно следует избегать попадания стеклоочищающей жидкости в зазоры между его фрагментами для предотвращения повреждения слоя амальгамы.</li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией зеркалам и зеркальному панно.</p>'
      image: ""

    - title: "Душевые кабины"
      description: '<p>Мы изготавливаем душевые перегородки, раздвижные и распашные душевые двери из высокопрочного и безопасного закалённого стекла 8мм. Используем только тщательно отобранную многолетним опытом фурнитуру производства Германии и Тайваня. По желанию, стёкла душевых кабин после монтажа могут быть обработаны специальным гидрофобным покрытием. </p>
      <div class="service-modal__attention">
        <p><strong>Обратите, пожалуйста, внимание:</strong></p>
        <ul>
          <li>Замер зоны установки душевой кабины должен проводиться в финальной стадии ремонта ванной комнаты (смонтированы поддон, плитка, установлены примыкающие к душевой кабине умывальник, унитаз, полотенцесушитель и пр.)</li>
          <li>При замере зоны душевой необходимо уведомить замерщика о прохождении коммуникаций (электропроводки, труб с водой, водоотведения) в зоне монтажа. </li>
          <li>Следует учесть, что стеклянные душевые не могут абсолютно блокировать проникновение воды за периметр, небольшие протечки возможны, прежде всего это касается тех случаев, когда отсутствует уклон пола для слива воды, душевая сделана без поддона, прямой поток направлен непосредственно на зону петель или зону примыкания магнитов.</li>
        </ul>
      </div>
      <p>&nbsp;</p><p><a class="service-modal__pdf-link" href="#" target="_blank">Смотреть pdf</a> с подробной информацией по душевым кабинам.</p>'
      image: ""
