context:
  mods: [about-intro]
  sectionConfig:
    title: Что мы производим
  productCategories:
    component: "list-item--product"
    nestedMods: [product,product-horizontal]
    listItems:
    - icon: /assets/images/catalog/1.png
      label: Трубы и фитинги для внутренней канализации из полипропилена
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Двухслойные гофрированные трубы и фитинги для двухслойных трубопроводов
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Трубы для фитинги для наружной канализации
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Трубы и фитинги для внутренней канализации из полипропилена с улучшенным шумо-поглощением
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Дренажные трубы из ПНД
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Трубопроводы для холодного водоснабжения из ПНД
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Трубы и фитинги для горячего и холодного водоснабжения и отопления ППР
      link: /product/link-to-product
    - icon: /assets/images/catalog/1.png
      label: Компрессионные фитинги для холодного водоснабжения
      link: /product/link-to-product
    bootstrap:
      cols: col-12 col-md-6 col-lg-4 col-xl-3
