handle: about-intro
context:
  mods: [about-intro]
  sectionConfig:
    title: О Нас
  description: "<p><strong>Компания «ПОЛИТЭК»</strong> основана в 1999 году для реализации программы ЖКХ и является лидером по производству полимерных трубопроводов для водоснабжения, отопления, канализации и дренажа.</p>
  <p>Производственные комплексы размещены в <strong>г. Одинцово</strong> Московской области и в <strong>г.Тула</strong>. Общая площадь производственных площадей компании
составляет более 40 тыс.м2</p>
  <p>На протяжении всей деятельности Компания демонстрирует стремительный рост, увеличивая многократно выпуск уникальной продукции высокого качества, соответствующего лучшим мировым аналогам.</p>
  <p><strong>Компанией «ПОЛИТЭК» накоплен уникальный опыт
в реализации таких проектов, как:</strong></p>
<ul>
  <li>Реконструкция спортивных комплексов «Лужники» и «Локомотив»</li>
  <li>Реконструкция Павелецкого вокзала, г. Москва</li>
  <li>Строительство олимпийских объектов к 2014 г., г. Сочи</li>
  <li>Строительство Гольф-клуба, г. Москва</li>
  <li>Строительство жилого комплекса «Алые паруса», г. Москва</li>
</ul>
<p>
совместно с компаниями: «Главмосстрой», Балтийская строительная компания, ДСК-1, ДСК-2, ДОН-Строй, «ПИК», «Мортон», а так же крупнейшими застройщиками в более чем <span>80 регионах России и республиках Казахстан, Белоруссия, Армения, Молдова,
Таджикистан и др.</span>
</p>
"
