handle: catalog-3
context:
  mods: [product-group]
  productList:
# product-1
  - title: Фитинги из ПП для внутренней канализации
    id: fiting_dlya_vnutrennei_kanalizatii
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-1/product-photo1.png
      link: /assets/images/catalog/3/product-1/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-1/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-1/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-2
  - title: Крестовины
    id: krestoviny
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-3
  - title: Муфты двухраструбные
    id: mufty_dvuhtrubnye
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-4
  - title: Муфты ремонтные
    id: mufty_remontnye
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-5
  - title: Отводы
    id: otvody
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-6
  - title: Отводы 11 с выходом на 50
    id: otvody_11_s_vyhodom_na_50
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-7
  - title: Патрубки компенсационные
    id: patrubki_compensationnye
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
# product-8
  - title: Переходы на чугун (Таперы)
    id: perehody_na_chugun
    productPhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-photo1.png
      link: /assets/images/catalog/3/product-2/product-photo1.png
    productSchemePhoto:
      mods: [with-link]
      src: /assets/images/catalog/3/product-2/product-scheme-photo1.png
      link: /assets/images/catalog/3/product-2/product-scheme-photo1.png
    textDescription: "Полипропиленовая заглушка <strong>«Политэк»</strong> — соединительный фитинг для пластиковых труб. С этой заглушкой вы сможете закрыть и загерметизировать трубы на любой срок. Изделие используется в работе с водопроводом или системой отопления."
    advantages:
    - Экологичная
    - Прочная
    - Устойчивая к перепадам температур и нагреву;
    - Влагоустойчивая;
    - Стойкая к воздействию коррозии и агрессивных химических соединений.
    addToCart:
      image: /assets/images/icons/addToCart.png
      label: Добавить в корзину
      mods: [with-image, secondary]
