context:
  site:
    title: 24 ways
    handle: 24ways
    description: 24 ways is the advent calendar for web geeks. Each day throughout December we publish a daily dose of web design and development goodness to bring you all a little Christmas cheer.
    feed: https://feeds.feedburner.com/24ways
    theme_color: "#f04"
  theme:
    year: [348, 344, 340, 336, 332, 328, 324, 320, 316, 312, 308, 304, 300, 296, 292, 288]
