context:
  strongCellsIds:
    - 1
    - 6
    - 7
  transparentCellsIds:
    - 8
    - 9
    - 10
  thead:
    - Изделие
    - Артикул
    - Вес (кг)
    - Объем (м<sup>3</sup>)
    - Кол-во в <br/>упаковке (шт)
    - Цена за шт. <br />(руб)
    - Ваша цена <br />за шт. (руб)
    - Кол-во <br />упаковок
    - Кол-во <br />штук
    - Стоимость
  rows:
    - cells:
      - 100 мм
      - 411000
      - 0,066
      - 0,009
      - 40
      - 29,04
      - 28,04
      - component: spinner
        config:
      - component: form-input--with-addon-text
        config:
          value: 143
          title: 100mm
      - component: price-cell
        config:
          price: 11000


    - cells:
      - 50 мм
      - 405000
      - 0,013
      - 0,003
      - 60*
      - 15,68
      - 14,99
      - component: spinner
        config:
      - component: form-input--with-addon-text
        config:
          disabled: true
          value: 143
          title: 50mm
      - component: price-cell
        config:
          price: 11200

    - cells:
      - 40 мм
      - 411000
      - 0,066
      - 0,009
      - 40
      - 29,04
      - 28,04
      - component: spinner
        config:
      - component: form-input--with-addon-text
        config:
          value: 143
          title: 100mm
      - component: price-cell
        config:
          price: 11000

    - cells:
      - 32 мм
      - 404000
      - 0,066
      - 0,009
      - 40
      - 29,04
      - 28,04
      - component: spinner
        config:
      - component: form-input--with-addon-text
        config:
          value: 143
          title: 100mm
          disabled: true
      - component: price-cell
        config:
          price: 11000

variants:
  - name: pricetable
    context:
      mods: [pricetable]
