context:
  title: "About 24 ways"
  section: about
  sections:
  - section: benefits
  - section: catalog
  - section: about
  - section: partners
  - section: news
  # - component: img-responsive
  #   config:
  #     src: /assets/images/pages/home/politek-banner.png
