context:
  mods: [production-totals]
  totalsList:
    component: "list-item--only-caption_extended"
    nestedMods: [only-caption_extended,with-border-gradient]
    bootstrap:
      cols: col-12 col-sm-6 col-md-12 col-lg-6 mb-3 mb-sm-0 mb-md-3 mb-lg-0
    bodyFontGradient: true
    listItems:
    - caption:
        body: 40000
        bottom: тыс. кв. м.
      label: Общая площадь всех производственных площадей в Туле и Одинцово
    - caption:
        body: 56000
        bottom: тонн в год
      label: Проектная мощность нашего оборудования


  trademarks:
    introText: "<strong>Мы изготавливаем продукцию
на оборудовании известных мировых марок:</strong>"
    items:
      component: "list-item"
      nestedMods: ["trademark"]
      bootstrap:
        cols: col-6 col-sm-4 mb-3
        last: col-12 mb-3
        rowClass: align-items-center trademarks-list
      listItems:
        - icon: "/assets/images/trademarks/engel.png"
        - icon: "/assets/images/trademarks/km.png"
        - icon: "/assets/images/trademarks/ifw.png"
        - icon: "/assets/images/trademarks/koch.png"
        - icon: "/assets/images/trademarks/sika.png"
        - icon: "/assets/images/trademarks/demag.png"
        - icon: "/assets/images/trademarks/wiba.png"

  productionImages:
    - src: "/assets/images/production/1.png"
    - src: "/assets/images/production/2.png"
    - src: "/assets/images/production/3.png"
    - src: "/assets/images/production/4.png"
