name: navigation
label: Менюшка в шапке
collated: true
default: desktop
variants:
- name: desktop
  context:
    modifier: desktop
- name: mobile
  context:
    modifier: mobile
context:
  pages:
  - title: Главная
    url: /components/preview/home
  - title: Каталог
    url: /components/preview/catalog
    subpages:
      - title: трубы и фитинги для внутренней канализации из пп
        url: /components/preview/catalog-2
      - title: двухслойные трубы и фитинги для двухслойных трубопроводов
        url: /components/preview/catalog-2
      - title: трубы и фитинги из пп для с улучшенным шумо-поглощенем
        url: /components/preview/catalog-2
      - title: двухслойные трубопроводы повышенной жесткости из пнд
        url: /components/preview/catalog-2
      - title: трубопроводы для водоснабжения из пнд
        url: /components/preview/catalog-2
      - title: трубы и фитинги для горячего/холодного водоснабжения
        url: /components/preview/catalog-2
      - title: компрессионные фитинги для холодного водоснабжения
        url: /components/preview/catalog-2
  - title: О компании
    url: /components/preview/about
    subpages:
      - title: О нас
        url: /components/preview/about
      - title: Производство
        url: /components/preview/production
      - title: Новости
        url: /components/preview/news
      - title: Отзывы
        url: /components/preview/testimonials
  - title: Для партнеров
    url: /components/preview/dlja-partnerov
    subpages:
      - title: Рекламные и информационные материалы
        url: /components/preview/promo
      - title: Условия хранения продукции
        url: /components/preview/terms
      - title: Сертификация
        url: /components/preview/certificates
  - title: Проектировщикам и монтажникам
    url: /components/preview/certificates
    subpages:
      - title: Чертежи
        url: /components/preview/certificates
      - title: Техническая информация
        url: /components/preview/terms
      - title: Снипы и госты
        url: /components/preview/gosts
  - title: Карта дилеров
    url: /components/preview/dealers
  - title: Контакты
    url: /components/preview/contacts
